### ISSUE TITLE
Archive current Environmental Scan and create a placeholder page for the archived site

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#147]

**Comment by GentrySteven** [comment]
See link: https://web.archive.org/web/20201202032415/https://dlfmetadataassessment.github.io/EnvironmentalScan

Some of our links, e.g. Data Quality Committee, don't immediately point to a resource when selected...I'm wondering if, in some cases, the link itself (e.g. https://web.archive.org/web/20201202032415/https://web.archive.org/web/20160901075956/https://pro.europeana.eu/page/data-quality-committee) is proving problematic due to the fact that there are (effectively) two Wayback/Internet Archive links in a single url, as demonstrated in this example. 

However, I'd see this more of a minor issue.

**Comment by GentrySteven** [comment]
Tentatively assigning this one to myself.
