### ISSUE TITLE
Create and update text for "About" page

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#165]
Draft version to go here

**Comment by northernlibrarian** [comment]
About
Welcome to the [Digital Library Federation (DLF) Assessment Interest Group (AIG) Metadata Working Group](https://wiki.diglib.org/Assessment:Metadata), also known as the DLF Metadata Assessment Working Group.

Mission
The DLF Metadata Assessment Working Group strives to collaboratively build guidelines, best practices, tools, and workflows around the evaluation and assessment of metadata used by and for digital libraries and repositories. We fulfill this mission by supporting discussions of metadata assessment and quality control, sharing metadata assessment approaches, and fostering a community of dedicated metadata assessment professionals.

The DLF Metadata Assessment Working Group creates high-level outputs that metadata workers from all walks of life can employ for their various metadata assessment needs.

As such, our efforts focus on how to measure, evaluate, and assess metadata as it exists in various digital library systems.

We hope that this resource offers a way for fellow metadata professionals to perform their own assessment of metadata practices; understand the results; and–ultimately–decide on a path that both enhances metadata quality and leads to a better understanding of one’s collections.

Organization
The DLF Metadata Assessment Working Group currently consists of the following sub-groups:

Metadata Quality Benchmarks.
Tools.
Website.

Current Project Focus

The 2020 DLF Metadata Assessment Working Group’s efforts focused on:

Updating the environmental scan [link needs to be added].
Writing a white paper about [benchmarks in metadata quality](http://dlfmetadataassessment.github.io/assets/WhitePaper_SurveyofBenchmarksinMetadataQuality.pdf).
Updating the metadata tools repository.
Updating the DLF Metadata Assessment Working Group’s website.

Prior Efforts
See the [DLF Metadata Assessment Working Group’s wiki page](https://wiki.diglib.org/Assessment:Metadata) for prior years’ goals and deliverables.

Project Limitations
This resource provides metadata professionals with a plain language, high-level resource for assessing descriptive metadata in digital collections.

Due to the wide range of digital collections, users, and institutions, this tool does not offer prescriptive recommendations for metadata.

Future Efforts
As our research efforts continue, we hope to expand our efforts to include related topics like:

Other kinds of metadata, such as structural, administrative, and technical metadata.
Assessment of the utility and importance of metadata.
Amelioration efforts to address harmful descriptive metadata as it relates to description of people and groups.
The qualitative state of metadata currently used.
Metadata beyond the digital repository.

As a member of the DLF community, we abide by the [DLF Code of Conduct](https://www.diglib.org/about/code-of-conduct/).

**Comment by northernlibrarian** [comment]
We should probably evaluate the project/tool limitations section and see if we still want it.
