### ISSUE TITLE
Create text for "Take Part" page

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#166]
Draft text

**Comment by hmc4** [comment]
_Below is the text I've written so far. I can edit the Take Part page and commit the changes if we think they're OK. I wondered whether we want to keep the feedback form here; I think it's too much for this page. Also, I am hazy on whether we want to link back to the DLF wiki; there are already so many links--but maybe we envision this site as superseding that one?_

The DLF AIG Metadata Working Group is open to anyone interested in collaborating on guidelines, best practices, tools, and workflows for the assessment of metadata used by and for digital libraries and repositories. See the [Projects] (https://dlfmetadataassessment.github.io/Sandbox/Projects) page for examples of past and ongoing projects. Other potential ways to get involved include reviewing relevant presentations and publications and updating this website.

The group holds working meetings from January through the DLF Forum in November. These 45-minute meetings take place every other Thursday, beginning at 10:15 AM Pacific/11:15 AM Mountain/12:15 PM Central/1:15 PM Eastern. Subgroups may hold additional meetings as needed.

To join, visit our [Google Group] (https://groups.google.com/forum/#!forum/dlf-aig-metadata-assessment-working-group).

**Comment by GentrySteven** [comment]
@hmc4 - I like this text! Although I wonder if it makes sense shorten/combine the last two sentences in the first paragraph (e.g. "See the [Projects] (https://dlfmetadataassessment.github.io/Sandbox/Projects) page for examples of current projects that you can get involved with, such as reviewing relevant presentations and publications and updating this website"), since potential volunteers wouldn't be able to participate in completed projects?

I know that in our [2020 recommendations re: restructuring the website](https://docs.google.com/document/d/1rs14512aP_3v9q419lgr_2YhiAXzHLnlKfg1qm_XQqE/edit), there had been an emphasis on more specificity rather than less for the "Take Part" page...but I think providing general info on two tasks/projects that are unlikely to change (lit review and website updates) will make maintaining this page much easier. I think the aforementioned recommendations on yearly website reviews could be folded into what Staci, Gabi, and myself are working on, since that's more  documentation related.

I also agree re: the Google Form - if we retain the form at all, it probably ought to be added to the page specifically pertaining to literature reviews. However, I wonder how often the form has been used since its inception--if the form hasn't been used tremendously, we could either point folks to the Google Group or something else that's fairly low maintenance (maybe an email/alias, per Shaun's recommendation in our 3/10 meeting).

Finally, I think your point about linking to the wiki raises some interesting questions about how we want to direct newcomers when they visit our Jekyll site (e.g. do we primarily point folks to the Google Group and only rarely point to the Wiki, which contains more high level info?). Personally, I think pointing to the [Google Group](https://groups.google.com/g/dlf-aig-metadata-assessment-working-group) makes more sense if we want people to broadly get involved. @kateefly, what are your thoughts - and do you think that questions about whether we should point more to the wiki or Google Group warrant being discussed during our sub-group meeting?

**Comment by hmc4** [comment]
I'll add a sentence pointing people to Zotero to add bib entries (see Publications and Presentations page) and remove Google form.

**Comment by hmc4** [comment]
_Update text as follows. Also, please remove the Google form per group consensus._

The DLF AIG Metadata Working Group is open to anyone interested in collaborating on guidelines, best practices, tools, and workflows for the assessment of metadata used by and for digital libraries and repositories. See the [Projects] (https://dlfmetadataassessment.github.io/Sandbox/Projects) page for examples of current projects to join, such as updating this website or reviewing notable presentations and publications.

The group holds working meetings from January through the DLF Forum in November. These 45-minute meetings take place every other Thursday, beginning at 10:15 AM Pacific/11:15 AM Mountain/12:15 PM Central/1:15 PM Eastern. Subgroups may hold additional meetings as needed.

To join the group, visit our [Google Group] (https://groups.google.com/forum/#!forum/dlf-aig-metadata-assessment-working-group).

To recommend a relevant presentation or publication, please add the citation to our [Metadata Assessment Zotero Group] (https://www.zotero.org/groups/488224/metadata_assessment).

**Comment by kateefly** [comment]
Resolved by commit 5051f3ebd69f436fd1fdb2799c378c4cb2d7eb65
