### ISSUE TITLE
Viewing the new site in a local environment on a Windows machine

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#280]
@kateefly's test failed, @sgolds15 's succeeded. @kateefly will need to run a clean install to see if that fixes the issue and possibly test with someone else with a Windows environement. See pr #279 for more details

**Comment by plampron2** [comment]
I'm not sure if this is the same issue that I'm having, but when I tried to open the site locally (windows) I got this error:

error `/' not found

I found this (https://stackoverflow.com/questions/56100280/how-to-fix-error-not-found-error-about-jekyll-in-localhost4000), and commenting out the baseurl line worked for me. I'm not sure if we need that line?

**Comment by sgolds15** [comment]
Hi @plampron2, I think if you keep (i.e., don’t comment out) the baseurl line, do a `bundle exec jekyll serve`, then navigate to http://localhost:4000/Sandbox/ in your browser, you should be able to see it. Does your terminal output say something like `Server address: http://127.0.0.1:4000/Sandbox/`?

The baseurl should be set in this case since the repo lives in the /Sandbox subpath of the dlfmetadataassessment.github.io domain. We _will_ need to comment out that line for the production site, though.

**Comment by plampron2** [comment]
Thanks @sgolds15 that did work. I've never had to do that before with the sandbox!

**Comment by GentrySteven** [comment]
I should add that I can view the new site on my computer and I'm running a Windows machine

**Comment by kateefly** [comment]
So I think I found the problem and it's an odd one - it's not Windows, it's Git Bash. When I try to view in a local environment using Git Bash, it fails. When I use Command Line, it succeeds. Are others using Git Bash or something else?

**Comment by GentrySteven** [comment]
I've been using the command line
